services:
  temporal:
    image: temporalio/server:1.25.0
    container_name: ${PROJECT_PREFIX}-temporal
    environment:
      DB: postgresql
      DB_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PWD: ${POSTGRES_PASSWORD}
      POSTGRES_SEEDS: ${PROJECT_PREFIX}-postgres
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development.yaml
      ENABLE_ES: false
      ES_SEEDS: ""
      ES_VERSION: ""
    ports:
      - "${TEMPORAL_PORT:-7233}:7233"
      # Web UI port removed for minimal setup
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "tctl", "--address", "temporal:7233", "cluster", "health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional Temporal UI - enable with profile for debugging
  temporal-ui:
    image: temporalio/ui:2.26.2
    container_name: ${PROJECT_PREFIX}-temporal-ui
    environment:
      TEMPORAL_ADDRESS: ${PROJECT_PREFIX}-temporal:7233
      TEMPORAL_CORS_ORIGINS: http://localhost:3000
    ports:
      - "${TEMPORAL_UI_PORT:-8085}:8080"
    depends_on:
      temporal:
        condition: service_healthy
    restart: unless-stopped
    profiles:
      - debug
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


