services:
  temporal:
    image: temporalio/auto-setup:1.25.0
    container_name: temporal
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PWD=${POSTGRES_PASSWORD}
      - POSTGRES_SEEDS=postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - ENABLE_ES=false
    ports:
      - "${TEMPORAL_PORT:-7233}:7233"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "tctl --address $$(hostname -i):7233 cluster health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional Temporal UI - enable with profile for debugging
  temporal-ui:
    image: temporalio/ui:2.26.2
    container_name: temporal-ui
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CORS_ORIGINS: http://localhost:3000
    ports:
      - "${TEMPORAL_UI_PORT:-8085}:8080"
    depends_on:
      temporal:
        condition: service_healthy
    restart: unless-stopped
    profiles:
      - debug
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


