services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT_PREFIX}-postgres
    env_file:
      - ../../.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # Additional PostgreSQL configurations
      POSTGRES_INITDB_ARGS: "--data-checksums"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      # Mounting the data volume and configuration files
      - postgres-data:/var/lib/postgresql/data
      # Mounting custom configuration file
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
      # Mounting initialization scripts
      - ./config/init:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

volumes:
  postgres-data:
    name: ${PROJECT_PREFIX}-postgres-data
