services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres
    env_file:
      - ../../.env
    environment:
      # PostgreSQL variables are loaded from env_file above
      # Additional PostgreSQL configurations
      POSTGRES_INITDB_ARGS: "--data-checksums"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      # Mounting the data volume and configuration files
      - postgres-data:/var/lib/postgresql/data
      # Mounting custom configuration file
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
      # Mounting initialization scripts
      - ./config/init:/docker-entrypoint-initdb.d
    networks:
      - backend-internal
    # Port not exposed externally - internal service only
    # ports:
    #   - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U app -d app",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

volumes:
  postgres-data:
    name: postgres-data
