services:
  keydb:
    image: eqalpha/keydb:latest
    container_name: ${PROJECT_PREFIX}-keydb
    env_file: ../../.env
    volumes:
      - keydb-data:/data
      - ./config/keydb.conf:/etc/keydb/keydb.conf
    ports:
      - "${KEYDB_PORT:-6379}:6379"
    restart: unless-stopped
    command: keydb-server /etc/keydb/keydb.conf --requirepass "${KEYDB_PASSWORD}"
    healthcheck:
      test:
        [
          "CMD",
          "keydb-cli",
          "-a",
          "${KEYDB_PASSWORD}",
          "ping",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
volumes:
  keydb-data:
    name: ${PROJECT_PREFIX}-keydb-data
