services:
  orchestration-api:
    build:
      context: ./orchestration-api
      dockerfile: Dockerfile
      target: development
    volumes:
      # Mount source code for hot-reloading in development
      - ./orchestration-api/src:/app/src
      - ./orchestration-api/tsconfig.json:/app/tsconfig.json
      # Use named volume to preserve node_modules from container
      - orchestration_node_modules:/app/node_modules

volumes:
  orchestration_node_modules:

